# Build and publish documentation

name: publish-prod

# Controls when the workflow will run
on: 
  push:
    branches:    
      - master
  workflow_dispatch:
    branches:    
      - master

jobs:

  build:
    runs-on: ubuntu-latest      
    env:
      SRC_DIR: ./public
      DEST_DIR: /var/www/docs.groupdocs.cloud/html

    steps:
      - uses: actions/checkout@v2

      - name: Install Hugo
        run: |
          curl -LO https://github.com/gohugoio/hugo/releases/download/v0.101.0/hugo_extended_0.101.0_Linux-64bit.deb
          sudo dpkg -i hugo_extended_0.101.0_Linux-64bit.deb
          
      - name: Run and build Hugo
        run: |              
          hugo --minify --config config-geekdoc.toml
        # mv ${{ env.SRC_DIR }}/product-sitemap.xml ${{ env.SRC_DIR }}/sitemaps/total.xml   
      
      - name: Deploy documentation
        uses: nogsantos/scp-deploy@master
        with:
          src: ${{ env.SRC_DIR }}/*
          host: ${{ secrets.DOCS_SSH_HOST }}
          remote: ${{ env.DEST_DIR }}
          user: ${{ secrets.DOCS_SSH_USER }}
          key: ${{ secrets.DOCS_SSH_KEY }}     

